name: peticioneshttpdart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

dependencies:
  http: ^0.13.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0


